---
- name: Deploy Resume-Builder 
  hosts: all
  tasks:
    - name: Pull docker image of Resume Builder
      docker_image:
        name: takshpatel/resume-builder:latest
        source: pull

    - name: Start minikube
      command: 
        cmd: minikube start

    - name: Create the resume-builder deployment and service
      command: 
        cmd: minikube kubectl -- apply -f k8s-config/

    - name: Update deployment with new pods if image updated
      command:
        cmd: minikube kubectl -- rollout restart deployment.apps/resume-builder-deployment
      