---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder-deployment
  labels:
    app: resume-builder
spec:
  selector:
    matchLabels:
      app: resume-builder
  replicas: 2
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: resume-builder
    spec:
      containers:
      - name: resume-builder
        image: takshpatel/resume-builder:latest
        ports:
        - containerPort: 9000